<script>
  import Report from "../../../components/Report.svelte";
  import type { PageData } from './$types';

  export let data: PageData;
  $: ({ report, path } = data);
</script>

<svelte:head>
  <title>rcv.report: {report.info.jurisdictionName} / {report.info.name} / {report.info.date.substr(0, 4)}</title>

  <meta property="og:title" content="{report.info.jurisdictionName} / {report.info.name}" />
  <meta property="og:image" content={"https://r.moxy.social/ykZcSLKZUq/ranked/fb.png/" + path.join("/")} />
  <meta property="twitter:card" content="summary_large_image" />
  <meta property="twitter:creator" content="@paulgb" />
  <meta property="twitter:title" content="{report.info.jurisdictionName} / {report.info.name}" />
  <meta property="twitter:image" content={"https://r.moxy.social/ykZcSLKZUq/ranked/twitter.png/" + path.join("/")} />
</svelte:head>

<div class="wide container">
<Report {report} />
<hr />
<div class="row"><p style="font-style: italic;">
  This report was generated by <a href="https://rcv.report/">rcv.report</a>
  and may be reproduced under <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY</a>.
  Learn more <a href="https://rcv.report/about">about rcv.report</a>.
</p></div>
</div>

<a style="display:none;" href={"/card/" + path.join("/")}>card</a>