<script>
  import Report from "../../../components/Report.svelte";

  export let data;
  $: ({ report, path } = data);
  
  // Add null safety for report data
  $: reportInfo = report?.info || {};
  $: title = reportInfo.jurisdictionName && reportInfo.name && reportInfo.date 
    ? `rcv.report: ${reportInfo.jurisdictionName} / ${reportInfo.name} / ${reportInfo.date.substr(0, 4)}`
    : 'rcv.report';
  $: ogTitle = reportInfo.jurisdictionName && reportInfo.name 
    ? `${reportInfo.jurisdictionName} / ${reportInfo.name}`
    : 'RCV Report';
</script>

<svelte:head>
  <title>{title}</title>

  <meta property="og:title" content="{ogTitle}" />
  <meta property="og:image" content={"https://r.moxy.social/ykZcSLKZUq/ranked/fb.png/" + (path || '')} />
  <meta property="twitter:card" content="summary_large_image" />
  <meta property="twitter:creator" content="@paulgb" />
  <meta property="twitter:title" content="{ogTitle}" />
  <meta property="twitter:image" content={"https://r.moxy.social/ykZcSLKZUq/ranked/twitter.png/" + (path || '')} />
</svelte:head>

<div class="wide container">
<Report {report} />
<hr />
<div class="row"><p style="font-style: italic;">
  This report was generated by <a href="https://rcv.report/">rcv.report</a>
  and may be reproduced under <a href="https://creativecommons.org/licenses/by/2.0/">CC-BY</a>.
  Learn more <a href="https://rcv.report/about">about rcv.report</a>.
</p></div>
</div>

<a style="display:none;" href={"/card/" + path}>card</a>